packages:
  - packages/**
  - frontend/**
  - backend/**
  - '!**/build'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
