/**
 * Defines the structure for a single validation error message,
 * typically generated by VineJS or a similar validation library.
 */
export type ValidationError = {
  /** The human-readable error message. */
  message: string
  /** The field or property that failed validation. */
  field: string
  /** The specific validation rule that failed (e.g., 'required', 'email'). */
  rule: string
  /** The index of the item in an array that failed validation. */
  index?: number
  /** Any additional metadata associated with the error. */
  meta?: Record<string, any>
}
